#!/bin/bash

# bash-n-client - bash library for connect-n game clients
#
# Copyright (C) 2019  Christian Garbs <mitch@cgarbs.de>
# Licensed under GNU GPL v3 or later.
#
# This file is part of bash-n.
#
# bash-n is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bash-n is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bash-n.  If not, see <http://www.gnu.org/licenses/>.

############################

# overwrite these hooks with your own strategy

# gets called when it is our turn
# RETURN the column number [1-7] of your move
calculate_move()
{
    die "no implementation of calculate_move() - overwrite this function!"
}

# gets called when the server has received a move in the current game
# $1 CLIENT NAME that made the move
# $2 COLUMN [1-7] where the move was made
record_move()
{
    die "no implementation of record_move() - overwrite this function!"
}

# gets called when a new game starts - use this to init or reset game state
# $1 CLIENT NAME of our opponent
game_start()
{
    die "no implementation of game_start() - overwrite this function!"
}

# gets called when a game ends
# $1 RESULT is one of [WIN|DRAW|LOSE]
# $2 CLIENT NAME that scored the result
# $3 REASON of the result
game_end()
{
    die "no implementation of game_end() - overwrite this function!"
}

############################

bash_n_state=UNDEFINED

# $* MESSAGE
die()
{
    log "$@"
    exit 1
}

# $* MESSAGE
log()
{
    echo "$*" >&2
}

# $1 COMMAND to send
# $* ARGUMENTS to send
send()
{
    local IFS=';'
    echo "$*"
}

# $1 SEASON HASH
on_new_season()
{
    local hash=$1
    bash_n_state=SEASON
    send JOIN "$hash"
}

# $1 OPPONENT
on_new_game()
{
    local opponent=$1
    bash_n_state=GAME
    game_start "$opponent"
}

# $1 TURN HASH
on_execute_turn()
{
    local hash=$1
    calculate_move
    send INSERT $? "$hash"
}

# $1 RESULT is one of [WIN|DRAW|LOSE]
# $2 CLIENT NAME that scored the result
# $3 REASON of the result
on_game_result()
{
    local result=$1 who=$2 why=$3
    bash_n_state=SEASON
    game_end "$result" "$who" "$why"
}

# $1 NAME of the client
start_client()
{
    local name=$1
    
    bash_n_state=CONNECTING
    send REGISTER "$name"

    while IFS=\; read -ra line; do
	local cmd=${line[0]}
	case "$bash_n_state-$cmd" in
	    CONNECTING-NEW\ SEASON)
		on_new_season "${line[1]}"
		;;
	    SEASON-NEW\ GAME)
		on_new_game "${line[1]}"
		;;
	    GAME-YOURTURN)
		on_execute_turn "${line[1]}"
		;;
	    GAME-TOKEN\ INSERTED)
		record_move "${line[1]}" "${line[2]}"
		;;
	    GAME-RESULT)
		on_game_result "${line[1]}" "${line[2]}" "${line[3]}"
		;;
	    *)
		die "received unknown command <$cmd> in state <$bash_n_state>"
		;;
	esac
    done
}
