#!/bin/bash

# bash-n-slothbot - very simple bot to demonstrate the bash-n-client library
#
#    slothbot implements this simple and stupid strategy:
#       time out on every move
#
#    To connect to a SERVER on PORT via UDP, run this script like this:
#    $ socat udp:SERVER:PORT exec:bash-n-simplebot
#
# Copyright (C) 2019  Christian Garbs <mitch@cgarbs.de>
# Licensed under GNU GPL v3 or later.
#
# This file is part of bash-n.
#
# bash-n is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bash-n is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bash-n.  If not, see <http://www.gnu.org/licenses/>.
# very simple bot to demonstrate the bash-n-client library

source bash-n-client

calculate_move()
{
    sleep 0.3
}

record_move()
{
    :
}

game_start()
{
    :
}

game_end()
{
    echo "$@"
}

start_client bash-n-slothbot
