#!/bin/bash

# bash-n-client - bash library for connect-n game clients
#
# Copyright (C) 2019  Christian Garbs <mitch@cgarbs.de>
# Licensed under GNU GPL v3 or later.
#
# This file is part of bash-n.
#
# bash-n is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bash-n is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bash-n.  If not, see <http://www.gnu.org/licenses/>.

bash_n_state=UNDEFINED

# $* MESSAGE
die()
{
    echo "$*" >&2
    exit 1
}

# $1 COMMAND to send
# $* ARGUMENTS to send
send()
{
    local IFS=';'
    echo "$*"
}

# $1 SEASON HASH
on_new_season()
{
    bash_n_season=$1
    bash_n_state=SEASON
    send JOIN "$bash_n_season"
}

# $1 OPPONENT
on_new_game()
{
    bash_n_opponent=$1
    bash_n_state=GAME
}

# $1 NAME of the client
start_client()
{
    local name=$1
    
    bash_n_state=CONNECTING
    send REGISTER "$name"

    while IFS=\; read -ra line; do
	local cmd=${line[0]}
	case "$bash_n_state-$cmd" in
	    CONNECTING-NEW\ SEASON)
		on_new_season "${line[1]}"
		;;
	    SEASON-NEW\ GAME)
		on_new_game "${line[1]}"
		;;
	    *)
		die "received unknown command <$cmd> in state <$bash_n_state>"
		;;
	esac
    done
}
